# Generated by Django 6.0.1 on 2026-01-27 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopters', '0001_initial'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='adopters.adopter')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='animals.animal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
